metadata:
  name: Android Hooks for Testing
  version: 1
  author: frooky dev
  platform: Android

# default settings from DEFAULT_FROOKY_SETTINGS: FrookySettings 
# settings:
#   hookSettings:
#     stackTraceLimit: 0
#     stackTraceFilter: []
#   decoderSettings:
#     hashCode: false
#     maxDepth: 10
#     maxItems: 100
#     decoder: undefined
#     decoderArg: undefined
#     argFilter: undefined

hookCollection:
  - javaClass: org.owasp.mastestapp.MastgTest
    hooks:
    - receiveNestedObjectArray


# expected: all hooks should inherite the settings from default