metadata:
  name: Test Settings Android
  description: |
    This frooky config uses different kind of settings:

      1. Global Settings

        Global settings can be of the type `HookSettings` and `DecoderSettings`. They apply to all hooks and their decoders (Parameter and Return Type), if they are not already set locally.

        Example: 

        ```
        settings:
          hookSettings:
            stackTraceLimit: 10
            stackTraceFilter: ['^(?!android).*']
          decoderSettings:
            maxDepth: 5
            maxItems: 100
        ``` 

      2. Hook and Decoder Settings 

        Hook and decoder settings define the behavior of the local hook. 

        Example: 
        
        ```
        <specific-hook>
          hookSettings:
            stackTraceLimit: 10
            stackTraceFilter: ['^(?!android).*']
          decoderSettings:
            maxDepth: 5
            maxItems: 100
        ```

      3. Parameter Settings

        Parameter settings (`ParamSettings`) define when a parameter is decoded (`direction`), as well as the settings defined in `DecoderSettings`.

        Example: 
        
        ```
        direction: out
        maxDepth: 5
        maxItems: 100
        ```

      4. Return Type Settings

        Return type settings are `DecoderSettings` applied when the return value is decoded

        Example: 
        
        ```
        maxDepth: 5
        maxItems: 100
        ```
  version: 1
  author: frooky dev
  platform: Android

# global settings for the hooks in this hook file.
settings:
  hookSettings:
    stackTraceLimit: 10
    stackTraceFilter: ['^(?!android).*']   # Stack trace filters to apply.
  decoderSettings:
    maxDepth: 1                       # Sets the cutoff limit for the recursion depth when decoding nested data structures, such as nested arrays, lists, sets, maps, structs etc.
    maxItems: 11                      # Sets the limit of how many elements of a enumerable data structures, such as arrays, lists, dictionaries etc. are decoded

hookCollection:
  # simple method declaration
  - javaClass: org.owasp.mastestapp.MastgTest
    hooks:
      - receiveBoolean

  # object with ONLY name provided, technically the same form as the one before
  - javaClass: org.owasp.mastestapp.MastgTest
    hooks:
      - method: receiveByte


  # PARTIAL local hook settings take priority over global setting, simple function declaration
  - javaClass: org.owasp.mastestapp.MastgTest
    hookSettings:
      stackTraceLimit: 2
    decoderSettings:
      maxItems: 22
    hooks:
      - receiveShort
      - receiveInt

  # PARTIAL local hook settings take priority over global setting, simple function declaration
  - javaClass: org.owasp.mastestapp.MastgTest
    hookSettings:
      stackTraceLimit: 3
    decoderSettings:
      maxItems: 33
    hooks:
      - method: receiveLong

  # PARTIAL local hook settings take priority over global setting, object with ONLY symbol provided
  - javaClass: org.owasp.mastestapp.MastgTest
    hookSettings:
      stackTraceLimit: 4
    decoderSettings:
      maxItems: 44
    hooks:
    - receiveFloat
    - receiveDouble


  # PARTIAL local parameter settings take priority over global setting, form [type, settings]
  - javaClass: org.owasp.mastestapp.MastgTest
    hookSettings:
      stackTraceLimit: 0
    hooks:
    - method: receiveIntArray
      overloads:
      - params:
        - ["[I", {maxItems: 55}]

  # PARTIAL local parameter settings take priority over global setting, form [type, name, settings]
  - javaClass: org.owasp.mastestapp.MastgTest
    hooks:
    - method: receiveNestedPrimitivesArray
      overloads:
      - params:
        - ["[[[I", nestedIntegerInput ]

  # complex common java types
  - javaClass: org.owasp.mastestapp.MastgTest
    hooks:
    - receiveBigInteger
    - receiveBigDecimal
    - receiveList
    - receiveMap
    - receiveSet
    - receiveEnum
