// Generated by ts-to-zod
import { z } from "zod";

import { decoderSettingsSchema } from "./frookySettings.zod";

export const decodableSchema = z.object({
    type: z.string(),
    name: z.string().optional(),
    declaringClass: z.string().optional(),
    settings: decoderSettingsSchema
});

export const directionSchema = z.union([z.literal("in"), z.literal("out"), z.literal("inout")]);

export const paramSchema = decodableSchema.extend({
    direction: directionSchema
});

export const retTypeSchema = decodableSchema;
