// Generated by ts-to-zod
import { z } from "zod";

export const hookSettingsSchema = z.object({
    maxStackFrames: z.number().min(0),
    nativeStackTrace: z.boolean(),
    platformStackTrace: z.boolean(),
    callerFilter: z.array(z.string()),
    early: z.boolean()
});

export const decoderConfigSchema = z.object({
    constants: z.union([z.record(z.string(), z.number()), z.string()]).optional()
});

export const javaDecoderNameSchema = z.union([z.literal("string"), z.literal("base64"), z.literal("hashCode"), z.literal("intentFlag"), z.literal("intentUriFlag"), z.literal("constants"), z.literal("bitmask"), z.literal("getters")]);

export const nativeBitmaskPresetNameSchema = z.union([z.literal("openFlags"), z.literal("mmapProt"), z.literal("mmapFlags"), z.literal("dlopenFlags"), z.literal("socketType")]);

export const nativeConstantsPresetNameSchema = z.literal("socketDomain");

export const nativeDecoderNameSchema = z.union([z.literal("string"), z.literal("base64"), z.literal("utf16"), z.literal("errno"), z.literal("fd"), z.literal("constants"), z.literal("bitmask"), z.literal("nullTerminated"), nativeBitmaskPresetNameSchema, nativeConstantsPresetNameSchema]);

export const decoderNameSchema = z.union([javaDecoderNameSchema, nativeDecoderNameSchema]);

export const decoderArgValueSchema = z.union([z.string(), z.number()]);

export const decoderArgsSchema = z.object({
    length: decoderArgValueSchema.optional(),
    offset: decoderArgValueSchema.optional()
});

export const baseDecoderSettingsSchema = z.object({
    maxDepth: z.number().min(1),
    maxItems: z.number().min(1),
    decoder: decoderNameSchema.optional()
});

export const decoderSettingsSchema = baseDecoderSettingsSchema.extend({
    decoderArgs: decoderArgsSchema.optional(),
    config: decoderConfigSchema.optional(),
    argFilter: z.array(z.string()).optional()
});

export const frookySettingsSchema = z.object({
    hookSettings: hookSettingsSchema,
    decoderSettings: baseDecoderSettingsSchema
});
