// Generated by ts-to-zod
import { z } from "zod";

import { frookyMetadataSchema as inputFrookyMetadataSchema } from "./frookyMetadata.zod";
import { inputJavaHookCollectionSchema } from "./inputJavaHookCollection.zod";
import { inputObjcHookCollectionSchema } from "./inputObjcHookCollection.zod";
import { inputSwiftHookCollectionSchema } from "./inputSwiftHookCollection.zod";
import { inputNativeHookCollectionSchema } from "./inputNativeHookCollection.zod";
import { inputFrookySettingsSchema } from "./inputSettings.zod";

export const inputFrookyConfigSchema = z.object({
    metadata: inputFrookyMetadataSchema.optional(),
    settings: inputFrookySettingsSchema.optional(),
    hookCollection: z.array(z.union([inputJavaHookCollectionSchema, inputObjcHookCollectionSchema, inputSwiftHookCollectionSchema, inputNativeHookCollectionSchema]))
});
