// Generated by ts-to-zod
import { z } from "zod";

export const hookSettingsSchema = z.object({
    maxStackFrames: z.number().min(0),
    stackTraceFilter: z.array(z.string()),
    nativeStackTrace: z.boolean(),
    platformStackTrace: z.boolean()
});

export const decoderArgValueSchema = z.union([z.string(), z.number()]);

export const decoderArgsSchema = z.object({
    length: decoderArgValueSchema.optional(),
    offset: decoderArgValueSchema.optional()
});

export const decoderSettingsSchema = z.object({
    maxDepth: z.number().min(1),
    maxItems: z.number().min(1),
    decoder: z.string().optional(),
    decoderArgs: decoderArgsSchema.optional(),
    constants: z.record(z.string(), z.number()).optional(),
    argFilter: z.array(z.string()).optional()
});

export const frookySettingsSchema = z.object({
    hookSettings: hookSettingsSchema,
    decoderSettings: decoderSettingsSchema
});
