// Generated by ts-to-zod
import { z } from "zod";

export const hookSettingsSchema = z.object({
    maxStackFrames: z.number().min(0),
    stackTraceFilter: z.array(z.string()),
    nativeStackTrace: z.boolean(),
    platformStackTrace: z.boolean()
});

export const javaDecoderNameSchema = z.union([z.literal("string"), z.literal("hashCode"), z.literal("intentFlag"), z.literal("intentUriFlag"), z.literal("constant"), z.literal("flags"), z.literal("getters")]);

export const nativeFlagsPresetNameSchema = z.union([z.literal("openFlags"), z.literal("mmapProt"), z.literal("mmapFlags"), z.literal("dlopenFlags"), z.literal("socketType")]);

export const nativeEnumPresetNameSchema = z.literal("socketDomain");

export const nativeDecoderNameSchema = z.union([z.literal("string"), z.literal("utf16"), z.literal("errno"), z.literal("fd"), z.literal("enum"), z.literal("flags"), z.literal("nullTerminated"), nativeFlagsPresetNameSchema, nativeEnumPresetNameSchema]);

export const decoderNameSchema = z.union([javaDecoderNameSchema, nativeDecoderNameSchema]);

export const decoderArgValueSchema = z.union([z.string(), z.number()]);

export const decoderArgsSchema = z.object({
    length: decoderArgValueSchema.optional(),
    offset: decoderArgValueSchema.optional()
});

export const decoderSettingsSchema = z.object({
    maxDepth: z.number().min(1),
    maxItems: z.number().min(1),
    decoder: decoderNameSchema.optional(),
    decoderArgs: decoderArgsSchema.optional(),
    constants: z.record(z.string(), z.number()).optional(),
    argFilter: z.array(z.string()).optional()
});

export const frookySettingsSchema = z.object({
    hookSettings: hookSettingsSchema,
    decoderSettings: decoderSettingsSchema
});
