// Generated by ts-to-zod
import { z } from "zod";

import { inputParamSchema, inputRetTypeSettingsSchema } from "./inputDecodableTypes.zod";
import { inputDecoderSettingsSchema, inputHookSettingsSchema } from "./inputSettings.zod";

export const inputOverloadSchema = z.object({
    params: z.array(inputParamSchema),
    retType: inputRetTypeSettingsSchema.optional()
});

export const inputJavaHookDetailsSchema = z.object({
    method: z.string(),
    overloads: z.array(inputOverloadSchema).optional(),
    hookSettings: inputHookSettingsSchema.optional(),
    decoderSettings: inputDecoderSettingsSchema.optional()
});

export const inputJavaHookSchema = z.union([z.string(), z.tuple([z.string(), inputDecoderSettingsSchema]), inputJavaHookDetailsSchema]);

export const inputJavaHookCollectionSchema = z.object({
    type: z.literal("java"),
    javaClass: z.string(),
    classLoader: z.string().optional(),
    hooks: z.array(inputJavaHookSchema),
    hookSettings: inputHookSettingsSchema.optional(),
    decoderSettings: inputDecoderSettingsSchema.optional()
});
