// Generated by ts-to-zod
import { z } from "zod";

import { inputParamSchema, inputRetTypeSchema } from "./inputDecodableTypes.zod";
import { inputDecoderSettingsSchema, inputHookSettingsSchema } from "./inputSettings.zod";

export const inputNativeHookNormalizedSchema = z.object({
    symbol: z.string(),
    module: z.string(),
    params: z.array(inputParamSchema).optional(),
    retType: inputRetTypeSchema.optional(),
    hookSettings: inputHookSettingsSchema.optional(),
    decoderSettings: inputDecoderSettingsSchema.optional()
});

export const inputNativeHookSchema = z.union([z.string(), inputNativeHookNormalizedSchema]);

export const inputNativeHookGroupSchema = z.object({
    type: z.literal("native"),
    module: z.string(),
    hooks: z.array(inputNativeHookSchema),
    hookSettings: inputHookSettingsSchema.optional(),
    decoderSettings: inputDecoderSettingsSchema.optional()
});
