// Generated by ts-to-zod
import { z } from "zod";

import { directionSchema } from "./decodable.zod";
import { decoderSettingsSchema, hookSettingsSchema } from "./frookySettings.zod";

export const inputHookSettingsSchema = hookSettingsSchema.partial();

export const inputDecoderSettingsSchema = decoderSettingsSchema.partial();

export const inputParamSettingsSchema = decoderSettingsSchema.partial().and(z.object({
    direction: directionSchema.optional()
}));

export const inputFrookySettingsSchema = z.object({
    hookSettings: inputHookSettingsSchema.optional(),
    decoderSettings: inputDecoderSettingsSchema.optional()
});
