// Generated by ts-to-zod
import { z } from "zod";

import { decoderSettingsSchema, hookSettingsSchema } from "./frookySettings.zod";
import { inputParamSchema, inputRetTypeSettingsSchema } from "./inputDecodableTypes.zod";
import { inputDecoderSettingsSchema, inputHookSettingsSchema } from "./inputSettings.zod";

export const inputObjcHookNormalizedSchema = z.object({
    objcClass: z.string(),
    method: z.string(),
    params: z.array(inputParamSchema).optional(),
    retType: inputRetTypeSettingsSchema.optional(),
    hookSettings: hookSettingsSchema.optional(),
    decoderSettings: decoderSettingsSchema.optional()
});

export const inputObjcHookSchema = z.union([z.string(), z.tuple([z.string(), decoderSettingsSchema]), inputObjcHookNormalizedSchema]);

export const inputObjcHookCollectionSchema = z.object({
    type: z.literal("objc"),
    objcClass: z.string(),
    hooks: z.array(inputObjcHookSchema),
    hookSettings: inputHookSettingsSchema.optional(),
    decoderSettings: inputDecoderSettingsSchema.optional()
});
