// Generated by ts-to-zod
import { z } from "zod";

import { inputParamSchema, inputRetTypeSchema } from "./inputDecodableTypes.zod";
import { inputDecoderSettingsSchema, inputHookSettingsSchema } from "./inputSettings.zod";

export const inputNativeHookBaseSchema = z.object({
    params: z.array(inputParamSchema).optional(),
    retType: inputRetTypeSchema.optional(),
    hookSettings: inputHookSettingsSchema.optional(),
    decoderSettings: inputDecoderSettingsSchema.optional()
});

export const inputNativeSymbolHookSchema = inputNativeHookBaseSchema.extend({
    symbol: z.string(),
    offset: z.never().optional()
});

export const inputNativeOffsetHookSchema = inputNativeHookBaseSchema.extend({
    offset: z.union([z.string(), z.number()]),
    symbol: z.never().optional()
});

export const inputNativeHookDetailsSchema = z.union([inputNativeSymbolHookSchema, inputNativeOffsetHookSchema]);

export const inputNativeHookSchema = z.union([z.string(), z.tuple([z.string(), inputDecoderSettingsSchema]), inputNativeHookDetailsSchema]);

export const inputNativeHookCollectionSchema = z.object({
    type: z.literal("native"),
    module: z.string(),
    hooks: z.array(inputNativeHookSchema),
    hookSettings: inputHookSettingsSchema.optional(),
    decoderSettings: inputDecoderSettingsSchema.optional()
});
