// Generated by ts-to-zod
import { z } from "zod";

import { decoderSettingsSchema, hookSettingsSchema } from "./frookySettings.zod";
import { inputParamSchema, inputRetTypeSettingsSchema } from "./inputDecodableTypes.zod";
import { inputDecoderSettingsSchema, inputHookSettingsSchema } from "./inputSettings.zod";

export const inputSwiftMethodHookSchema = z.object({
    method: z.string(),
    params: z.array(inputParamSchema).optional(),
    retType: inputRetTypeSettingsSchema.optional(),
    hookSettings: hookSettingsSchema.optional(),
    decoderSettings: decoderSettingsSchema.optional()
});

export const inputSwiftClassHookNormalizedSchema = inputSwiftMethodHookSchema.and(z.object({
    swiftClass: z.string()
}));

export const inputSwiftStructHookNormalizedSchema = inputSwiftMethodHookSchema.and(z.object({
    swiftStruct: z.string()
}));

export const inputSwiftEnumHookNormalizedSchema = inputSwiftMethodHookSchema.and(z.object({
    swiftEnum: z.string()
}));

export const inputSwiftHookNormalizedSchema = z.union([inputSwiftClassHookNormalizedSchema, inputSwiftStructHookNormalizedSchema, inputSwiftEnumHookNormalizedSchema]);

export const inputSwiftHookSchema = z.union([z.string(), z.tuple([z.string(), decoderSettingsSchema]), inputSwiftHookNormalizedSchema]);

const inputSwiftHookCollectionBaseSchema = z.object({
    hooks: z.array(inputSwiftHookSchema),
    hookSettings: inputHookSettingsSchema.optional(),
    decoderSettings: inputDecoderSettingsSchema.optional()
});

export const inputSwiftClassHookCollectionSchema = inputSwiftHookCollectionBaseSchema.extend({
    swiftClass: z.string()
});

export const inputSwiftStructHookCollectionSchema = inputSwiftHookCollectionBaseSchema.extend({
    swiftStruct: z.string()
});

export const inputSwiftEnumHookCollectionSchema = inputSwiftHookCollectionBaseSchema.extend({
    swiftEnum: z.string()
});

export const inputSwiftHookCollectionSchema = z.union([inputSwiftClassHookCollectionSchema, inputSwiftStructHookCollectionSchema, inputSwiftEnumHookCollectionSchema]);

export const swiftOwnerSchema = z.union([z.object({
        swiftClass: z.string()
    }), z.object({
        swiftStruct: z.string()
    }), z.object({
        swiftEnum: z.string()
    })]);
