// Generated by ts-to-zod
import { z } from "zod";

import { directionSchema } from "./decodable.zod";
import { inputDecoderSettingsSchema, inputParamSettingsSchema } from "./inputSettings.zod";

export const inputParamObjectSchema = z.object({
    type: z.string(),
    name: z.string().optional(),
    direction: directionSchema.optional(),
    settings: inputDecoderSettingsSchema.optional()
});

export const inputParamSchema = z.union([z.string(), z.tuple([z.string(), z.string()]), z.tuple([z.string(), inputParamSettingsSchema]), z.tuple([z.string(), z.string(), inputParamSettingsSchema]), inputParamObjectSchema]);

export const inputRetTypeObjectSchema = z.object({
    type: z.string(),
    name: z.string().optional(),
    settings: inputDecoderSettingsSchema.optional()
});

export const inputRetTypeSchema = z.union([z.string(), z.tuple([z.string(), inputDecoderSettingsSchema]), inputRetTypeObjectSchema]);

export const inputRetTypeSettingsSchema = inputDecoderSettingsSchema;
