name: Setup Test Environment for Hosts
description: Download the current frooky host and install it
runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.14"

    - name: Download host artifact
      uses: actions/download-artifact@v8
      with:
        name: frooky-host
        path: dist

    - name: Install frooky and dev dependencies
      shell: bash
      run: |
        echo "Installing frooky"
        python -m pip install dist/*.whl

        echo "Installing dev dependencies from pyproject.toml"
        python -m pip install $(python -c "import tomllib; print(' '.join(tomllib.load(open('pyproject.toml', 'rb'))['project']['optional-dependencies']['dev']))")
